### ISSUE TITLE
plant uml rendering slow

### ISSUE THREAD

**Issue by xu4wang** [jhuix/vue-showdowns-editor#3]
I tried the sample file, modified the UML part, the editor was frozen for around 2 seconds after changes.

I guess it because the interaction with plantuml website.. is it possible to have plantuml picture generated locally?

**Comment by jhuix** [comment]
Yes, you're right.
Because the plantuml diagram is rendered asynchronously and remotely to the plantuml website (www.plantuml.com/plantuml) in the vue-showdowns-editor is a component of vue.js.

If you want to render locally, you need to integrate the component and install Java \ graphviz locally and redevelop it.

In the future, there will be plans to develop a local applications related to this component.

**Comment by xu4wang** [comment]
> In the future, there will be plans to develop a local applications related to this component.

if we just install a local plantuml-server
https://github.com/plantuml/plantuml-server

use the local server instead, the speed will be improved I guess.

**Comment by jhuix** [comment]
You can consider downloading the vscode extension named [MarkDown Preview Showdown (MDPS)](https://marketplace.visualstudio.com/items?itemName=jhuix.markdown-preview-showdown) developed by me.
The vscode extension provides the features of local rendering plantuml.
